config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'

  resources :entry_types
  resources :users
  resources :sessions

  resources :entries do
    resources :reminders
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :entry_type
  belongs_to :user
end

app/models/entry_type.rb
class EntryType < ApplicationRecord
  has_many :entries, class_name: "Entry"
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt

  has_many :entries, class_name: "Entry"

  def password
    @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/entries_controller.rb
require 'date'

class EntriesController < ApplicationController

  def index
    @entries = Entry.where(user_id: current_user.id)
  end

  def new
    @entry_types = EntryType.all
    @entry_types = @entry_types.map do |entry_type|
      [entry_type.name, entry_type.id]
    end
    @date_now = date_now
  end

  def create
    # Make some type of helper method for the controller
    @entry_types = EntryType.all
    @entry_types = @entry_types.map do |entry_type|
      [entry_type.name, entry_type.id]
    end
    @entry = Entry.new(entry_params)
    @entry.user_id = current_user.id
      if @entry.save
        redirect_to action: "index"
      else
        @error = "Entry creation was unsuccessful"
        render new_entry_path
      end
  end

  def show
    @entry = Entry.find_by_id(params[:id])
    @entry_type = @entry.entry_type
  end

  def edit
    # Break into another helper method
    @entry_types = EntryType.all
    @entry_types = @entry_types.map do |entry_type|
      [entry_type.name, entry_type.id]
    end
    @entry = Entry.find_by_id(params[:id])
  @date_now = date_now
  end

  def update
    # Make some type of helper method for the controller
    @entry_types = EntryType.all
    @entry_types = @entry_types.map do |entry_type|
      [entry_type.name, entry_type.id]
    end
    @entry = Entry.find_by_id(params[:id])
    @entry.assign_attributes(entry_params)
    if @entry.save
      redirect_to action: "index"
    else
      @error = "Entry creation was unsuccessful"
      render new_entry_path
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to action: "index"
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :entry_type_id, :date)
  end

  def date_now
    Date.today
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if @user = User.find_by_email(session_params[:email])
      if @user && @user.password == session_params[:password]
        session[:user_id] = @user.id
        redirect_to @user
      else
        @error = "Invalid input. Please try again."
        render new_session_path
      end
    else
      @error = "User not found."
      render new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  private

  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    if params[:user][:password] == params[:user][:confirm_password]
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        @error = "User creation was unsuccessful"
        render new_user_path
      end
    else
      @error = "Password does not match"
      render new_user_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/destroy.html.erb
<div class="container">
</div>

app/views/entries/edit.html.erb
<div class="container">
  <h1>Fill out the form below to create a new entry:</h1>


  <%= form_for :entry, url: "/entries/#{@entry.id}", :html => { :method => 'PATCH' } do |f| %>
    <%= f.label "Title:" %><br>
    <%= f.text_field :title, value: @entry.title %><br>
    <%= f.label "Description" %><br>
    <%= f.text_area(:description, value: @entry.description, size: "50x10") %><br>
    <%= f.select(:entry_type_id, options_for_select(@entry_types), {prompt: 'Select Type of Entry'}) %><br>
    <%= f.label "Date" %><br>
    <%= f.date_field :date, value: @date_now %>
    <%= f.submit "Create new entry" %>
  <% end %>

  <% if @error %>
    <p class="error"><strong><%= @error %></strong></p>
  <% end %>

  <h3><a href='/entry_types/new'>Click here to create a new type of entry</a></h3>
  <a href='/'>Home</a>
</div>

app/views/entries/index.html.erb
<div class="container">
  <h2>Welcome! Here are your gardening entries:</h2>
  <div class="entries-container">
    <table>
      <tr class="entries-headers">
        <th>Date</th>
        <th>Entry</th>
        <th>Edit</th>
        <th>Delete</th>
        <th>Get Reminder</th>
      </tr>
      <% if @entries %>
      <% @entries.each do |entry| %>

      <tr class="entries-list">
        <td class="entry-date"><%= entry.date.to_date %></td>
        <td class="entry-title"><%= link_to entry.title, entry_path(entry.id) %></td>
        <td class="edit-entry"><%= link_to "Edit", edit_entry_path(entry.id) %></td>
        <td class="delete-entry"><%= link_to "Delete", entry_path(entry.id), method: :delete %></td>
        <td>
          <!-- remember to refactor reminder button with Rails helper methods -->
          <form id='reminder-button' method="POST" action="/reminders">
            <input type="hidden" name="reminder_freq" value="<%= entry.entry_type.reminder_freq %>">
            <input type="hidden" name="entry_date" value="<%= entry.created_at %>">
            <input type="hidden" name="entry_type_name" value="<%= entry.entry_type.name %>">
            <input type="submit" value="Reminder" class="button">
          </form>
        </td>
      <% end %>
      </tr>
      <% end %>
    </table>
  </div>
</div>

  <%= form_for :entry, url: new_entry_path, :html => { :method => 'GET' } do |f| %>
    <%= f.submit "Create a new Entry" %>
  <% end %>

<!-- remember to include forecast_data at bottom of page -->

app/views/entries/new.html.erb
<div class="container">
  <h1>Fill out the form below to create a new entry:</h1>


  <%= form_for :entry, url: entries_path, :html => { :method => 'POST' } do |f| %>
    <%= f.label "Title:" %><br>
    <%= f.text_field :title %><br>
    <%= f.label "Description" %><br>
    <%= f.text_area(:description, size: "50x10") %><br>
    <%= f.select(:entry_type_id, options_for_select(@entry_types), {prompt: 'Select Type of Entry'}) %><br>
    <%= f.label "Date" %><br>
    <%= f.date_field :date, value: @date_now %>
    <%= f.submit "Create new entry" %>
  <% end %>

  <% if @error %>
    <p class="error"><strong><%= @error %></strong></p>
  <% end %>

  <h3><a href='/entry_types/new'>Click here to create a new type of entry</a></h3>
  <a href='/'>Home</a>
</div>

app/views/entries/show.html.erb
<div class="container">
  <h1>Title:</h1>
    <div>
    <%= @entry.title %>
    </div>
  <h2>Description:</h2>
    <div>
    <%= @entry.description %>
    </div>
  <h2>Date:</h2>
    <div>
    <%= @entry.date.to_date %>
    </div>
  <h2>Entry Type:</h2>
    <div>
    <%= @entry_type.name %>
    </div>
  <div>
  <a href='/'>Home</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherOrNot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
  <h2>Sign up to become a new user</h2>

  <%= form_for :user, url: users_path, :html => { :method => 'POST' } do |f| %>
    <%= f.label "First Name" %><br>
    <%= f.text_field :first_name %><br>
    <%= f.label "Last Name" %><br>
    <%= f.text_field :last_name %><br>
    <%= f.label "Email" %><br>
    <%= f.text_field :email %><br>
    <%= f.label "Password" %><br>
    <%= f.password_field :password %><br>
    <%= f.label "Confirm Password" %><br>
    <%= f.password_field :confirm_password %><br>
    <%= f.submit "Sign Up" %>
  <% end %>

  <% if @error %>
    <p class="error"><strong><%= @error %></strong></p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="first_name">Welcome, <%= @user.first_name %></h1>
  <h2>What do you want to do?</h2>
  <%= form_for(:session, url: session_path(session), :method => :delete) do |f| %>
    <%= f.submit :value => "Logout" %>
  <% end %>

  <%= form_for(:entry, url: entries_path, :method => 'GET') do |f| %>
    <%= f.submit :value => "View Entries" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <h1>Welcome to Weather or Not</h1>

  <h2>What would you like to do?</h2>
  <% if @current_user %>

  <%= form_for(:session, url: session_path(session), :method => :delete) do |f| %>
    <%= f.submit :value => "Logout" %>
  <% end %>

  <%= form_for(:entry, url: entries_path, :method => 'GET') do |f| %>
    <%= f.submit :value => "View Entries" %>
  <% end %>

  <% else %>

    <%= form_for :user, url: new_user_path, :html => { :method => 'GET' } do |f| %>
      <%= f.submit "Sign Up" %>
    <% end %>

    <%= form_for :session, url: new_session_path, :html => { :method => 'GET' } do |f| %>
      <%= f.submit "Login" %>
    <% end %>

  <% end %>

</div>